services:
  server:
    build:
      context: .
      dockerfile: Dockerfile  # Assuming your Dockerfile is named "Dockerfile"
      args:
        - IMAGE_NAME=session-rec
    ports:
      - 8000:8000
    env_file:
      - .env
    volumes:
      - .:/app
    develop:
      watch:
        - action: sync
          path: .
          target: /app
        - action: rebuild
          path: environment_cpu.yml
    command: ["conda", "run", "-n", "srec37", "python3", "main.py", "${JOB}","--config", "${CONFIG}"]